spring:
  datasource:
    url: ${BOOKING_DB_URL:jdbc:postgresql://localhost:5432/fithub_booking_db}
    username: ${BOOKING_DB_USERNAME:fithub}
    password: ${BOOKING_DB_PASSWORD:fithub}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
