spring:
  datasource:
    url: ${AUTH_DB_URL:jdbc:postgresql://localhost:5432/fithub_auth_db}
    username: ${AUTH_DB_USERNAME:fithub}
    password: ${AUTH_DB_PASSWORD:fithub}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
