export const adminResources = {
  users: {
    title: 'Utilizatori',
    endpoint: '/users',
    sortOptions: ['username', 'email'],
    fields: [
      { name: 'username', label: 'Username', required: true },
      { name: 'email', label: 'Email', type: 'email', required: true },
      { name: 'password', label: 'Parola', type: 'password', requiredOnCreate: true, minLength: 8, showInTable: false },
      { name: 'lastName', label: 'Nume', path: 'profile.lastName', required: true },
      { name: 'firstName', label: 'Prenume', path: 'profile.firstName', required: true },
      { name: 'phone', label: 'Telefon', path: 'profile.phone' },
      { name: 'enabled', label: 'Activ', type: 'checkbox' },
      { name: 'roles', label: 'Roluri', type: 'relationMulti', source: '/roles', optionLabel: 'name', valueKey: 'name', required: true },
    ],
  },
  locations: {
    title: 'Locatii',
    endpoint: '/locations',
    sortOptions: ['name', 'city'],
    fields: [
      { name: 'name', label: 'Nume', required: true },
      { name: 'address', label: 'Adresa', required: true },
      { name: 'city', label: 'Oras', required: true },
      { name: 'active', label: 'Activa', type: 'checkbox' },
    ],
  },
  rooms: {
    title: 'Sali',
    endpoint: '/rooms',
    sortOptions: ['name', 'capacity'],
    fields: [
      { name: 'location', label: 'Locatie', type: 'relation', source: '/locations', optionLabel: ['name', 'city'], required: true },
      { name: 'name', label: 'Nume', required: true },
      { name: 'capacity', label: 'Capacitate', type: 'number', required: true, min: 1 },
      { name: 'active', label: 'Activa', type: 'checkbox' },
    ],
  },
  trainers: {
    title: 'Antrenori',
    endpoint: '/trainers',
    sortOptions: ['lastName', 'email'],
    fields: [
      { name: 'lastName', label: 'Nume', required: true },
      { name: 'firstName', label: 'Prenume', required: true },
      { name: 'email', label: 'Email', type: 'email', required: true },
      { name: 'specialization', label: 'Specializare' },
      { name: 'active', label: 'Activ', type: 'checkbox' },
    ],
  },
  'class-types': {
    title: 'Tipuri clase',
    endpoint: '/class-types',
    sortOptions: ['name', 'difficultyLevel'],
    fields: [
      { name: 'name', label: 'Nume', required: true },
      { name: 'description', label: 'Descriere' },
      { name: 'difficultyLevel', label: 'Dificultate' },
    ],
  },
  classes: {
    title: 'Clase fitness',
    endpoint: '/classes',
    sortOptions: ['startTime', 'name'],
    fields: [
      { name: 'classType', label: 'Tip clasa', type: 'relation', source: '/class-types', optionLabel: ['name', 'difficultyLevel'], required: true },
      { name: 'trainer', label: 'Antrenor', type: 'relation', source: '/trainers', optionLabel: ['lastName', 'firstName'], required: true },
      { name: 'trainingRoom', label: 'Sala', type: 'relation', source: '/rooms', optionLabel: ['name', 'capacity'], required: true },
      { name: 'name', label: 'Nume', required: true },
      { name: 'startTime', label: 'Start', type: 'datetime-local', required: true, future: true },
      { name: 'endTime', label: 'Final', type: 'datetime-local', required: true, future: true, afterField: 'startTime', afterLabel: 'Start' },
      { name: 'capacity', label: 'Capacitate', type: 'number', required: true, min: 1 },
      { name: 'availableSlots', label: 'Locuri disponibile', type: 'number', min: 0 },
      { name: 'status', label: 'Status', placeholder: 'SCHEDULED', omitWhenEmpty: true },
    ],
  },
  'subscription-types': {
    title: 'Tipuri abonamente',
    endpoint: '/subscription-types',
    sortOptions: ['name', 'price'],
    fields: [
      { name: 'name', label: 'Nume', required: true },
      { name: 'description', label: 'Descriere' },
      { name: 'price', label: 'Pret', type: 'number', required: true, min: 0.01, step: '0.01' },
      { name: 'durationDays', label: 'Durata zile', type: 'number', required: true, min: 1 },
      { name: 'active', label: 'Activ', type: 'checkbox' },
    ],
  },
  clients: {
    title: 'Clienti',
    endpoint: '/clients',
    sortOptions: ['lastName', 'email'],
    fields: [
      { name: 'authUserId', label: 'ID user auth', type: 'number', required: true, min: 1 },
      { name: 'lastName', label: 'Nume', required: true },
      { name: 'firstName', label: 'Prenume', required: true },
      { name: 'email', label: 'Email', type: 'email', required: true },
      { name: 'phone', label: 'Telefon' },
    ],
  },
  subscriptions: {
    title: 'Abonamente clienti',
    endpoint: '/subscriptions',
    sortOptions: ['startDate', 'status'],
    fields: [
      { name: 'client', label: 'Client', type: 'relation', source: '/clients', optionLabel: ['firstName', 'lastName', 'email'], required: true },
      { name: 'subscriptionType', label: 'Tip abonament', type: 'relation', source: '/subscription-types', optionLabel: ['name', 'price'], required: true },
      { name: 'startDate', label: 'Data start', type: 'date', required: true },
      { name: 'endDate', label: 'Data final', type: 'date', required: true, afterField: 'startDate', afterLabel: 'Data start' },
      { name: 'status', label: 'Status', placeholder: 'ACTIVE', omitWhenEmpty: true },
    ],
  },
  payments: {
    title: 'Plati',
    endpoint: '/payments',
    sortOptions: ['paymentDate', 'status'],
    fields: [
      { name: 'client', label: 'Client', type: 'relation', source: '/clients', optionLabel: ['firstName', 'lastName', 'email'], required: true },
      { name: 'clientSubscription', label: 'Abonament', type: 'relation', source: '/subscriptions', optionLabel: ['id', 'status', 'endDate'] },
      { name: 'amount', label: 'Suma', type: 'number', required: true, min: 0.01, step: '0.01' },
      { name: 'paymentDate', label: 'Data plata', type: 'datetime-local', omitWhenEmpty: true },
      { name: 'status', label: 'Status', placeholder: 'PAID', omitWhenEmpty: true },
      { name: 'method', label: 'Metoda', placeholder: 'CARD', omitWhenEmpty: true },
    ],
  },
}
