export const adminResources = {
  users: {
    title: 'Utilizatori',
    endpoint: '/users',
    sortOptions: ['username', 'email'],
    fields: [
      { name: 'username', label: 'Username', required: true },
      { name: 'email', label: 'Email', type: 'email', required: true },
      { name: 'password', label: 'Parola', type: 'password' },
      { name: 'firstName', label: 'Prenume', required: true },
      { name: 'lastName', label: 'Nume', required: true },
      { name: 'phone', label: 'Telefon' },
      { name: 'enabled', label: 'Activ', type: 'checkbox' },
      { name: 'roles', label: 'Roluri', placeholder: 'ADMIN,USER' },
    ],
  },
  locations: {
    title: 'Locatii',
    endpoint: '/locations',
    sortOptions: ['name', 'city'],
    fields: [
      { name: 'name', label: 'Nume', required: true },
      { name: 'address', label: 'Adresa', required: true },
      { name: 'city', label: 'Oras', required: true },
      { name: 'active', label: 'Activa', type: 'checkbox' },
    ],
  },
  rooms: {
    title: 'Sali',
    endpoint: '/rooms',
    sortOptions: ['name', 'capacity'],
    fields: [
      { name: 'location', label: 'ID locatie', type: 'relation', required: true },
      { name: 'name', label: 'Nume', required: true },
      { name: 'capacity', label: 'Capacitate', type: 'number', required: true },
      { name: 'active', label: 'Activa', type: 'checkbox' },
    ],
  },
  trainers: {
    title: 'Antrenori',
    endpoint: '/trainers',
    sortOptions: ['lastName', 'email'],
    fields: [
      { name: 'firstName', label: 'Prenume', required: true },
      { name: 'lastName', label: 'Nume', required: true },
      { name: 'email', label: 'Email', type: 'email', required: true },
      { name: 'specialization', label: 'Specializare' },
      { name: 'active', label: 'Activ', type: 'checkbox' },
    ],
  },
  'class-types': {
    title: 'Tipuri clase',
    endpoint: '/class-types',
    sortOptions: ['name', 'difficultyLevel'],
    fields: [
      { name: 'name', label: 'Nume', required: true },
      { name: 'description', label: 'Descriere' },
      { name: 'difficultyLevel', label: 'Dificultate' },
    ],
  },
  classes: {
    title: 'Clase fitness',
    endpoint: '/classes',
    sortOptions: ['startTime', 'name'],
    fields: [
      { name: 'classType', label: 'ID tip clasa', type: 'relation', required: true },
      { name: 'trainer', label: 'ID antrenor', type: 'relation', required: true },
      { name: 'trainingRoom', label: 'ID sala', type: 'relation', required: true },
      { name: 'name', label: 'Nume', required: true },
      { name: 'startTime', label: 'Start', type: 'datetime-local', required: true },
      { name: 'endTime', label: 'Final', type: 'datetime-local', required: true },
      { name: 'capacity', label: 'Capacitate', type: 'number', required: true },
      { name: 'availableSlots', label: 'Locuri disponibile', type: 'number' },
      { name: 'status', label: 'Status', placeholder: 'SCHEDULED' },
    ],
  },
  'subscription-types': {
    title: 'Tipuri abonamente',
    endpoint: '/subscription-types',
    sortOptions: ['name', 'price'],
    fields: [
      { name: 'name', label: 'Nume', required: true },
      { name: 'description', label: 'Descriere' },
      { name: 'price', label: 'Pret', type: 'number', required: true },
      { name: 'durationDays', label: 'Durata zile', type: 'number', required: true },
      { name: 'active', label: 'Activ', type: 'checkbox' },
    ],
  },
  clients: {
    title: 'Clienti',
    endpoint: '/clients',
    sortOptions: ['lastName', 'email'],
    fields: [
      { name: 'authUserId', label: 'ID user auth', type: 'number', required: true },
      { name: 'firstName', label: 'Prenume', required: true },
      { name: 'lastName', label: 'Nume', required: true },
      { name: 'email', label: 'Email', type: 'email', required: true },
      { name: 'phone', label: 'Telefon' },
    ],
  },
}
